pipeline {
    agent any

    options {
        skipDefaultCheckout(true)
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/Sebaas1887/LemonCode-BootCamp-DevOps.git'
            }
        }

        stage('Compile') {
            steps {
                dir('04-cicd/jenkins-resources/calculator') {
                    sh 'chmod +x gradlew'
                    sh './gradlew compileJava'
                }
            }
        }

        stage('Unit Tests') {
            steps {
                dir('04-cicd/jenkins-resources/calculator') {
                    sh './gradlew test'
                }
            }
        }
    }
}